Korean Language Support
MrCrayfish/Controllable pull request #328
Opened 2022-08-30 14:06 UTC by kuroehanako

Some translations missed. but, necessary HUD Translations complete.

2022-08-31 03:39 UTC, MrCrayfish requested changes

2022-08-31 03:39 UTC, MrCrayfish commented on src/main/resources/assets/controllable/lang/ko_kr.json
> +    "controllable.key.previousCreativeTab": "이전 크리에이티브 탭 / 제작법 페이지,
Missing end quote

2022-08-31 03:39 UTC, MrCrayfish commented on src/main/resources/assets/controllable/lang/ko_kr.json
> +    "controllable.key.moveRight": "오른쪽으로 이동,
Missing end quote

2022-08-31 04:06 UTC, kuroehanako commented
I fixed some syntax errors.

2022-08-31 17:53 UTC, kuroehanako commented on src/main/resources/assets/controllable/lang/ko_kr.json
> +    "controllable.key.previousCreativeTab": "이전 크리에이티브 탭 / 제작법 페이지,
I fixed it.

2022-09-01 05:11 UTC, MrCrayfish approved these changes

2022-09-01 05:19 UTC, MrCrayfish commented
Is this considered ready to merge or are you going to be translating more?

2022-09-01 12:13 UTC, mjkim0727 commented
Merge now. I translated as possible as my english skill.

2022-09-03 17:16 UTC, kuroehanako commented
I ready to merge my commit.

2022-11-28 05:17 UTC, merged

2022-11-28 05:18 UTC, MrCrayfish commented
Thank you!

2023-07-01 08:59 UTC, MrCrayfish commented
Hey @mjkim0727, I am currently in the process of relicensing Controllable to a more suitable license. I would like your permission to relicense your contributions to Controllable under MIT.